### PR TITLE
Support database schema argument

### PR DESCRIPTION
**Pull request by narusemotoki**
Thank you! This is a great application!

---

Some RDB has multiple schemas, e.g. PostgreSQL.
`eralchemy -i ... -o ... -s test_schema`

Originaly, this is working.
```
CREATE TABLE test_table (
    id SERIAL PRIMARY KEY
);
```

I want to support this like table too.
```
CREATE SCHEMA test_schema;
CREATE TABLE test_schema.test_table (
    id SERIAL PRIMARY KEY
);
```

Schema argument is optional. If don't use it, Eralchemy will work with
the same as original.

test_schema

### CODE REVIEW

**Comment by Alexis-benoist** [comment]
Thanks for the PR!
Do you think that you can test this feature?

**Comment by narusemotoki** [comment]
@Alexis-benoist Tests are using SQLite. Unfortunately, it doesn't support schema. (right? I don't know a lot about that) So, if I write a test for the feature, we need to switch database from SQLite to PostgreSQL or something.
What do you think? Can I do that?

**Comment by Alexis-benoist** [comment]
We could do a specific test for this feature using pgsql.
We will have to look how to do it with Travis.
Sudo apt get install postgres or something like that.
I can't look this week but I will try this we!

**Comment by narusemotoki** [comment]
I will rewrite tests and add tests with PostgreSQL on this weekend.

**Comment by Alexis-benoist** [comment]
Thanks !

2015-10-14 10:37 GMT+02:00 Motoki Naruse <notifications@github.com>:

**Comment by Alexis-benoist** [comment]
:+1:

**Pull request merged**
