### PR TITLE
Update development setup for Python 3.7+

### PR DESCRIPTION
**Pull request by florimondmanca**
Refs #92 

This PR updates the test and CI setup so it is fully compatible with 3.7 both locally and on CI.

* Use postgres container on CI
* Switch all testing (local or CI) to `tox`
* Upgrade test dependencies to work on Python 3.7+ (tested on 3.8 and 3.10)
* Allow configuring a custom `DATABASE_URL`
* Update contributing instructions

### CODE REVIEW

**Comment by florimondmanca** [comment]
Hi @Alexis-benoist, I believe you ran CI for me for the first commit. Unfortunately GitHub does not seem to grant allowance for an entire PR; as I pushed a new commit, GitHub requires approval again. Might I be added as a collaborator on this repo? I'm willing to move this forward.

Also, I noticed this tool still supports Python 2.7 which is has long been EOL and has been dropped by psycopg2 on version 2.9. SQLAlchemy is longer than other projects to drop support, planned for 2.0. I believe we'll need to consider dropping support too for the health of this project.

**Comment by Alexis-benoist** [comment]
Hey,
Can you use your fork to be able to run it so you can work independently?

Le mer. 22 juin 2022, 11:11, Florimond Manca ***@***.***> a
écrit :

**Comment by florimondmanca** [comment]
Hi again @Alexis-benoist, thanks for the suggestion to run CI on my fork. I did lots of iterations on and ended up with the current state of this PR. Please see the PR description for some notes on the changes. Let me know what you think :)

**Comment by 12rambau** [comment]
@florimondmanca thanks a lot for your contribution, now that modifications from eralchemy2 have been merged back to the repository, your PR has become very much out of sync. I will revamp the packaging to reflect the changes you wanted to initiate.

**Pull request closed without merging**
