### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by pgjones**
A couple of minor fixes I've required to use this package.

### CODE REVIEW

**Comment by pgjones** [comment]
I think the test failure is unrelated to these changes.

**Comment by lukasmu** [comment]
This should fix [#80](https://github.com/Alexis-benoist/eralchemy/issues/80), correct?

**Comment by louis-vines** [comment]
I think this error is due to this change:
https://github.com/Alexis-benoist/eralchemy/commit/4f9dbdabd032bc293c1ab68174402af5954720d6

I'm wanting to contribute something to the project but my tests are failing with the same error. I'm not 100% sure the current code db_uri `postgresql://postgres/test` in the tests is valid

**Comment by cancan101** [comment]
Any chance to get this merged?

**Comment by maurerle** [comment]
This PR is obsolete, the changes of https://github.com/sturzaam/eralchemy/pull/1 are included in 34668762946a7334cc9659c28722a8143b83f2c9

This can be closed

**Pull request closed without merging**
