### PR TITLE
Provide a way to exclude tables and their resulting relationships

### PR DESCRIPTION
**Pull request by saschwarz**
I found I needed to exclude segments of our large database schema from diagrams and added the -x table table1 table2 CLI argument to exclude tables by name.

### CODE REVIEW

**Comment by Alexis-benoist** [comment]
Hey Steve,

Thanks for the PR!
I feel confortable with the tests which are solid. Though, I feel the implementation could be simpler. I think that we should filter the tables and relationships at [main:line147](https://github.com/Alexis-benoist/eralchemy/blob/master/eralchemy/main.py#L147) with a simple filter function.

If we want to add another type of input, we will have to reimplement the exclude another time.

What do you think?

Cheers,
Alexis.

**Comment by saschwarz** [comment]
I looked there initially but it wasn't as clear to me how to remove relationships for the tables that were removed. I'll take a look later this week.

**Comment by Alexis-benoist** [comment]
Why don't you do something like?
`[r for r in relationships if r.right_col not in tables_to_exclude and r.left_col not in tables_to_exclude]`

**Comment by saschwarz** [comment]
I pulled the filtering of excludes out into a simple function. It made it easier to write tests.

**Comment by Alexis-benoist** [comment]
Seems good!

**Pull request merged**
